# -*- coding: utf-8 -*-
"""Seminar_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rC8zohNKrsXJLkqAPaewrZdUIodrvBvj
"""

# В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

import pandas as pd
import random

lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'WhoAmi':lst})
data

data.loc[(data['WhoAmi'] == 'human'), 'human'] = 1
data.loc[(data['WhoAmi'] != 'human'), 'human'] = 0
data